CREATE TABLE IF NOT EXISTS `config_parameter` (
    `key` VARCHAR(64) PRIMARY KEY,
    `value` VARCHAR(256) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);