trade:
  target-pair: USD_JPY
  target-time-frame: MINUTE
  back-test: true
  available-balance-rate: 0.8
  max-candle-num: 100
  stop-limit: 0.08
  profit-limit: 0.15
  indicator-limit: 3
  buy-point-threshold: 1
  sell-point-threshold: 1
  api-cost: 0.002
  leverage: 20