INSERT INTO config_parameter (`key`, `value`)
VALUES
('CHART.COLLECT_TARGET_PAIRS', 'USD_JPY'),
('CHART.COLLECT_TARGET_TIME_FRAMES', '1m,15m,1h,4h,1d,1w'),
('TRADE.TARGET_PAIR', 'USD_JPY'),
('TRADE.BACK_TEST', 'false'),
('TRADE.TARGET_TIME_FRAME', '1h'),
('TRADE.MAX_CANDLE_NUM', '200'),
('TRADE.BUY_POINT_THRESHOLD', '2'),
('TRADE.SELL_POINT_THRESHOLD', '2'),
('TRADE.AVAILABLE_BALANCE_RATE', '0.8'),
('TRADE.LEVERAGE', '15.0'),
('TRADE.API_COST', '0.002'),
('TRADE.STOP_LIMIT', '0.08'),
('TRADE.PROFIT_LIMIT', '0.15');